global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "gateway"
    metrics_path: /metrics
    static_configs:
      - targets: ["gatewayd:8081"]

  - job_name: "auth"
    metrics_path: /metrics
    static_configs:
      - targets: ["authd:8081"]

  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:9464"]

  - job_name: "hello"
    metrics_path: /metrics
    static_configs:
      - targets: ["hellod:8081"]
