global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "gateway"
    metrics_path: /metrics
    static_configs:
      - targets: ["gatewayd:8081"]

  - job_name: "auth"
    metrics_path: /metrics
    static_configs:
      - targets: ["authd:8081"]

  - job_name: "hello"
    metrics_path: /metrics
    static_configs:
      - targets: ["hellod:8081"]
